# Generated by Django 4.0.4 on 2022-04-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_instance_instance_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='name',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
    ]
