# Generated by Django 4.0.4 on 2022-04-28 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_service_application_name_service_price_unit_per_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.application'),
        ),
    ]
