# Generated by Django 4.0.4 on 2022-05-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_application_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ami',
            field=models.TextField(default='1', max_length=255),
            preserve_default=False,
        ),
    ]
