# Generated by Django 4.0.4 on 2022-05-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_application_ami'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='state',
            field=models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('stopping', 'stopping'), ('stopped', 'stopped'), ('shutting-down', 'shutting-down'), ('terminated', 'terminated')], default='running', max_length=255),
            preserve_default=False,
        ),
    ]
