# Generated by Django 4.0.4 on 2022-05-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_service_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='state',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Running', 'Running'), ('Stopping', 'Stopping'), ('Stopped', 'Stopped'), ('Shutting-down', 'Shutting-down'), ('Terminated', 'Terminated')], max_length=255),
        ),
    ]
